### ISSUE TITLE
Conversion error, Jekyll 3.0.0

### ISSUE THREAD

**Issue by wjdp** [jekyll/jekyll-coffeescript#12]
Jekyll 3 upgrade in progress and getting the following when compiling my coffeescript, same environment builds under version 2 latest.

```
  Conversion error: Jekyll::Converters::CoffeeScript encountered an error while converting 'js/app.coffee':
                    SyntaxError: [stdin]:1:48: unexpected number
compile ((execjs):6633:19): SyntaxError: [stdin]:1:48: unexpected number (ExecJS::RuntimeError)
	from eval (<anonymous>:1:10)
	from print ((execjs):6644:8)
	from (execjs):6650:14
	from require../helpers.exports ((execjs):1:102)
	from Object.<anonymous> ((execjs):1:120)
	from Module._compile (module.js:456:26)
	from Object.Module._extensions..js (module.js:474:10)
	from Module.load (module.js:356:32)
	from Function.Module._load (module.js:312:12)
	from Function.Module.runMain (module.js:497:10)
	from startup (node.js:119:16)
	from node.js:902:3
	from /var/lib/gems/2.1.0/gems/execjs-2.6.0/lib/execjs/external_runtime.rb:39:in `exec'
	from /var/lib/gems/2.1.0/gems/execjs-2.6.0/lib/execjs/external_runtime.rb:21:in `eval'
	from /var/lib/gems/2.1.0/gems/execjs-2.6.0/lib/execjs/external_runtime.rb:46:in `call'
	from /var/lib/gems/2.1.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:78:in `compile'
	from /var/lib/gems/2.1.0/gems/jekyll-coffeescript-1.0.1/lib/jekyll/converters/coffeescript.rb:16:in `convert'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/convertible.rb:73:in `block in transform'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/convertible.rb:71:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/convertible.rb:71:in `reduce'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/convertible.rb:71:in `transform'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/convertible.rb:258:in `do_layout'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/page.rb:116:in `render'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:179:in `block in render'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:177:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:177:in `render'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:59:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/command.rb:28:in `process_site'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:60:in `build'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:35:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by wjdp** [comment]
Seems to be related to using `{% include...` in the main coffeescript file

**Comment by wjdp** [comment]
Error on my end, project uses a custom include tag (which I'd forgotten about) and due to changes in Jekyll's IncludeTag (tag_includes_dir -> resolved_includes_dir) it broke a bit.

**Comment by parkr** [comment]
Glad you got it fixed !
